---
AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Public S3 bucket and policies to store Lambda artifacts for use in this solution.

Parameters:
  BucketName:
    Type: String
    Default: aws-cognito-github-proxy-lambda-resources

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Ref BucketName
      LifecycleConfiguration:
        Rules:
          - Id: MultipartUploadRule
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      Tags:
        - Key: website
          Value: gaelcms.com
      VersioningConfiguration:
        Status: Enabled

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
            - 's3:GetObject'
            - 's3:GetObjectVersion'
            Effect: Allow
            Principal: "*"
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
